### PR TITLE
Log something, to ease debugging

### PR DESCRIPTION
**Pull request by alanjds**
Is very hard to understand what is _not_ going on without a single line on the logs.

### CODE REVIEW

**Comment by bdpiparva** [comment]
@alanjds - Please can you rebase the PR?

**Comment by jupe** [comment]
This would be very useful feature! Hard to fix something I cannot see..

**Comment by jtomaszewski** [comment]
I believe this can be closed thanks to https://github.com/gocd-contrib/gocd-build-status-notifier/pull/79 being merged.

**Comment by arvindsv** [comment]
Ok, thanks @jtomaszewski. Closing this.

**Pull request closed without merging**
